debug: false
auto-update: notify-only
world-selection: blacklist
world-list: []
always-yield-full-amount: false
require-signs: false

recipes:
  CHAINMAIL_BOOTS: IRON_INGOT:4
  CHAINMAIL_CHESTPLATE: IRON_INGOT:8
  CHAINMAIL_HELMET: IRON_INGOT:5
  CHAINMAIL_LEGGINGS: IRON_INGOT:7

  IRON_CHESTPLATE: IRON_INGOT:8
  IRON_LEGGINGS: IRON_INGOT:7
  IRON_HELMET: IRON_INGOT:5
  IRON_BOOTS: IRON_INGOT:4
  IRON_SWORD: IRON_INGOT:2
  IRON_HOE: IRON_INGOT:2
  IRON_AXE: IRON_INGOT:3
  IRON_PICKAXE: IRON_INGOT:3
  IRON_SPADE: IRON_INGOT:1
  GOLD_CHESTPLATE: GOLD_NUGGET:72
  GOLD_LEGGINGS: GOLD_NUGGET:63
  GOLD_HELMET: GOLD_NUGGET:45
  GOLD_BOOTS: GOLD_NUGGET:36
  GOLD_SWORD: GOLD_NUGGET:18
  GOLD_HOE: GOLD_NUGGET:18
  GOLD_AXE: GOLD_NUGGET:27
  GOLD_PICKAXE: GOLD_NUGGET:27
  GOLD_SPADE: GOLD_NUGGET:9
  DIAMOND_CHESTPLATE: DIAMOND:8
  DIAMOND_LEGGINGS: DIAMOND:7
  DIAMOND_HELMET: DIAMOND:5
  DIAMOND_BOOTS: DIAMOND:4
  DIAMOND_SWORD: DIAMOND:2
  DIAMOND_HOE: DIAMOND:2
  DIAMOND_AXE: DIAMOND:3
  DIAMOND_PICKAXE: DIAMOND:3
  DIAMOND_SPADE: DIAMOND:1
  STONE_SWORD: STONE:2
  STONE_HOE: STONE:2
  STONE_AXE: STONE:3
  STONE_SPADE: STONE:1
  STONE_PICKAXE: STONE:3
  SHEARS: IRON_INGOT:2
recipe-groups: